version: '3.4'
x-default: &default
  restart: always

services:
  api:
    <<: *default
    image: matteob99/tcstats-api:latest
    links:
      - db

  db:
    <<: *default
    image: postgres:11-alpine
    volumes:
      - type: volume
        source: db-tcstats-api
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  db-tcstats-api:
